version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  django: &django
    environment: &django_env
       DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE:-{{cookiecutter.django_settings}}.dev}"
       NO_MIGRATE: "1"
       NO_COLLECT_STATIC: "1"
       NO_STATICS: "1"
    volumes: &django_volumes
      {%-if cookiecutter.use_submodule_for_deploy_code %}
      - ./{{cookiecutter.deploy_project_dir}}/sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/sys/init.sh
      - ./{{cookiecutter.deploy_project_dir}}/sys/etc/supervisor.d:/code/etc/supervisor.d
      - ./{{cookiecutter.deploy_project_dir}}:/code/{{cookiecutter.deploy_project_dir}}
      {%-else %}
      - ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./sys/init.sh:/code/sys/init.sh
      - ./sys/etc/supervisor.d:/code/etc/supervisor.d
      {%- endif%}
{%- if not cookiecutter.no_lib %}
      - ./lib:/code/lib
{%- endif%}
      - ./local:/code/local
      - ./src:/code/src
{%- if not cookiecutter.no_private %}
      - ./private:/code/private
{%- endif%}
      - ./tox.ini:/code/tox.ini
      - ./.tox:/code/.tox
      - ./requirements.txt:/code/requirements.txt
      - ./requirements-dev.txt:/code/requirements-dev.txt
services:
  nginx: {<<: [ *bypass ]}
  backup: {<<: [ *bypass ]}
  {{cookiecutter.app_type}}:
    <<: [ *django ]
    environment:
      <<: [ *django_env ]
      IMAGE_MODE: fg
    ports:
      - "8000:8000"
{% if cookiecutter.with_celery %}
  celery-beat: &celery
    <<: [ *django ]
    environment:
      <<: [ *django_env ]
      IMAGE_MODE: celery_beat
  celery-worker:
    <<: [ *celery ]
    environment:
      <<: [ *django_env ]
      IMAGE_MODE: celery_worker
{% endif -%}
